package hu.elte.sbzbxr.phoneconnect.model.actions.helper;

public enum ActionType {
    JUST_CONNECTED,
    JUST_DISCONNECTED,
    FAIL_MESSAGE,

    BACKUP_FILE_FIRST_ARRIVED,
    FILE_TRANSFER_FIRST_ARRIVED,
    RESTORE_LIST_OF_AVAILABLE_BACKUPS,
    PIECE_OF_FILE_ARRIVED,
    LAST_PIECE_OF_FILE_ARRIVED,
    PING_ARRIVED,
    OUTGOING_FILE_TRANSFER_STARTED,

    PIECE_OF_FILE_SENT,
    LAST_PIECE_OF_FILE_SENT,
}
